alter table public.players
  add column if not exists date_of_birth date;

update public.jamaat_cities
set active = false
where name not in (
  'Atlanta',
  'Austin',
  'Bakersfield',
  'Boston',
  'Calgary',
  'Chicago',
  'Columbus',
  'Dallas',
  'Detroit',
  'Edmonton',
  'Houston',
  'Los Angeles',
  'Miami',
  'Minneapolis',
  'Mississauga',
  'Montreal',
  'New Jersey',
  'New York',
  'North Carolina',
  'Orange County',
  'Ottawa',
  'Philadelphia',
  'Plano',
  'Portland',
  'San Antonio',
  'San Diego',
  'San Francisco',
  'San Jose',
  'Seattle',
  'South Carolina',
  'South Jersey',
  'Tampa',
  'The Woodlands',
  'Toronto',
  'Vancouver',
  'Virginia',
  'Washington, D.C.'
);

insert into public.jamaat_cities (name, display_order, active)
values
  ('Atlanta', 1, true),
  ('Austin', 2, true),
  ('Bakersfield', 3, true),
  ('Boston', 4, true),
  ('Calgary', 5, true),
  ('Chicago', 6, true),
  ('Columbus', 7, true),
  ('Dallas', 8, true),
  ('Detroit', 9, true),
  ('Edmonton', 10, true),
  ('Houston', 11, true),
  ('Los Angeles', 12, true),
  ('Miami', 13, true),
  ('Minneapolis', 14, true),
  ('Mississauga', 15, true),
  ('Montreal', 16, true),
  ('New Jersey', 17, true),
  ('New York', 18, true),
  ('North Carolina', 19, true),
  ('Orange County', 20, true),
  ('Ottawa', 21, true),
  ('Philadelphia', 22, true),
  ('Plano', 23, true),
  ('Portland', 24, true),
  ('San Antonio', 25, true),
  ('San Diego', 26, true),
  ('San Francisco', 27, true),
  ('San Jose', 28, true),
  ('Seattle', 29, true),
  ('South Carolina', 30, true),
  ('South Jersey', 31, true),
  ('Tampa', 32, true),
  ('The Woodlands', 33, true),
  ('Toronto', 34, true),
  ('Vancouver', 35, true),
  ('Virginia', 36, true),
  ('Washington, D.C.', 37, true)
on conflict (name) do update set
  display_order = excluded.display_order,
  active = excluded.active;
